sudo: required
dist: xenial
services:
    - docker

before_install:
    - sudo apt update && sudo apt install make -y
    - git clone https://github.com/estesp/manifest-tool && cd manifest-tool && git checkout v0.9.0 && sudo make && sudo make install && cd .. && rm -Rf manifest-tool
    - docker run --rm --privileged multiarch/qemu-user-static:register
    - sudo apt install -y qemu qemu-user-static qemu-user binfmt-support

script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_LOGIN" --password-stdin
    - travis_wait 100 make build

deploy:
    provider: script
    script:
        - make publish latest
    on:
        branch: master
